baseURL = 'https://zigcc.github.io/'
languageCode = 'en-us'
title = 'Zig 语言中文社区'
theme = "hugo-xmin"

[[menu.main]]
  name = "主页"
  weight = 10
  url = "/"
[[menu.main]]
  name = "月刊"
  weight = 20
  url = "/monthly"
[[menu.main]]
  name = "论坛"
  weight = 30
  url = "https://zigcc.github.io/forum/"
# [[menu.main]]
#   name = "Tags"
#   weight = 3
#   url = "/tags"
# [[menu.main]]
#   name = "关于"
#   weight = 4
#   url = "/about"
# [[menu.main]]
#   name = "RSS"
#   weight = 50
#   url = "/index.xml"

[params]
  description = ""
  footer =  "@ 2022 [ZigCC](https://github.com/zigcc/zigcc.github.io). Licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)"
  dateFormat = "Jan 2, 2006"
  showThemeSwitcher =  true
  gitRepo = "https://github.com/zigcc/zigcc.github.io"
  [params.giscus]           # https://giscus.app/
    repo = "zigcc/zigcc.github.io"
    repoId = "R_kgDOHr7nSg"
    category = "Announcements"
    categoryId = "DIC_kwDOHr7nSs4CQUsK"
