name: Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.md"
      - "**.org"
      - ".github/workflows/**"
  push:
    branches:
      - main
    paths:
      - "**.md"
      - "**.org"
      - ".github/workflows/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Prettier check
        run: |
          make lint
